name: test_linkedin_login [Selenium-Test Continous Integration Work-Flow]

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Run commands
      - name: setup
        run: |
          echo -e "\n[start]: $(date) - upgrading, and installing firefox browser, python3.6.9, and pip..."
          sudo apt-get -y upgrade 2>/dev/null
          sudo apt-get update --fix-missing 2>/dev/null
          sudo apt-get install -yf firefox 2>/dev/null
          sudo apt-get install -yf python3 2>/dev/null
          sudo apt-get install -yf python3-pip 2>/dev/null
          echo -e "\n[done]: $(date) - upgrading, and installing firefox browser, python3.6.9, and pip..."
      - name: pip install Modules
        run: |
          echo -e "\n[start]: $(date) - pip installing from resources/requirements.txt"
          pip install -r resources/requirements.txt
          echo -e "\n[done]: $(date) - pip installing from resources/requirements.txt"
      - name: test_linkedin_login [unit-tests]
        env: 
          LINKEDIN_USERNAME: ${{secrets.LINKEDIN_USERNAME}}
          LINKEDIN_PASSWORD: ${{secrets.LINKEDIN_PASSWORD}}
        run: |
          echo -e "\n[start]: $(date) - python3 -m pytest -v tests/test_selenium_linkedin_login.py"
          python3 -m pytest -v tests/test_selenium_linkedin_login.py::test_linkedin_login
          echo -e  "\n[done]: $(date) - python3 -m pytest -v tests/test_selenium_linkedin_login.py"
